# Generated by Django 5.1.7 on 2025-03-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0002_alter_offer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseinfo',
            old_name='business_profile_count',
            new_name='user_count',
        ),
        migrations.RemoveField(
            model_name='baseinfo',
            name='profile',
        ),
    ]
