# Generated by Django 5.1.7 on 2025-03-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0008_offer_created_at_offer_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='business_user',
            new_name='user',
        ),
    ]
