# Generated by Django 5.1.7 on 2025-03-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offerImages/'),
        ),
    ]
